import numpy as np

from geo.simulation_engine import GeologySimulation
from geo.materials import MaterialType


def test_granite_does_not_melt_in_vacuum():
    """Granite painted into pure vacuum must not convert to magma after one step."""

    width = height = 60
    sim = GeologySimulation(width, height, log_level="INFO")

    # Wipe the autogenerated planet – start with pure SPACE & uniform 300 K.
    sim.material_types[:, :] = MaterialType.SPACE
    sim.temperature[:, :] = 300.0

    # Paint a granite blob near the top-centre.
    granite_center = (3, width // 2)  # (y, x)
    granite_radius = 5
    sim.material_processes_module.paint_blob(*granite_center, radius=granite_radius, material=MaterialType.GRANITE)

    # Advance one full physics step – includes settling & metamorphism.
    sim.step_forward()

    # Verify **all** cells of the granite blob remain granite.
    yy, xx = np.ogrid[:height, :width]
    g_mask = (xx - granite_center[1]) ** 2 + (yy - granite_center[0]) ** 2 <= granite_radius ** 2
    assert np.all(sim.material_types[g_mask] == MaterialType.GRANITE), "Granite blob should stay granite in vacuum." 